package server

var dashboardHTML = []byte(`<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Stockyard Parcel</title><style>:root{--bg:#1a1410;--surface:#241c15;--border:#3d2e1e;--rust:#c4622d;--leather:#8b5e3c;--cream:#f5e6c8;--muted:#7a6550;--text:#e8d5b0}*{box-sizing:border-box;margin:0;padding:0}body{background:var(--bg);color:var(--text);font-family:'JetBrains Mono',monospace,sans-serif;min-height:100vh}header{background:var(--surface);border-bottom:1px solid var(--border);padding:1rem 2rem;display:flex;align-items:center;gap:1rem}.logo{color:var(--rust);font-size:1.25rem;font-weight:700}.badge{background:var(--rust);color:var(--cream);font-size:0.65rem;padding:0.2rem 0.5rem;border-radius:3px;font-weight:600;text-transform:uppercase}main{max-width:1100px;margin:0 auto;padding:2rem}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin-bottom:2rem}.stat{background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:1.25rem;text-align:center}.stat-value{font-size:1.75rem;font-weight:700;color:var(--rust)}.stat-label{font-size:0.75rem;color:var(--muted);margin-top:0.25rem;text-transform:uppercase;letter-spacing:0.05em}.grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.card{background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:1.5rem}.card h2{font-size:0.85rem;color:var(--muted);text-transform:uppercase;letter-spacing:0.08em;margin-bottom:1rem}.form-row{display:flex;gap:0.5rem;margin-bottom:0.75rem;flex-wrap:wrap;align-items:flex-start}select,input,textarea{background:var(--bg);border:1px solid var(--border);color:var(--text);padding:0.5rem 0.75rem;border-radius:4px;font-family:inherit;font-size:0.85rem}.form-row select,.form-row input{flex:1}textarea{width:100%;min-height:80px;resize:vertical}.btn{background:var(--rust);color:var(--cream);border:none;padding:0.5rem 1rem;border-radius:4px;cursor:pointer;font-family:inherit;font-size:0.85rem;font-weight:600}.btn:hover{opacity:0.85}.btn-sm{padding:0.25rem 0.6rem;font-size:0.75rem}.btn-danger{background:#7a2020}table{width:100%;border-collapse:collapse;font-size:0.82rem}th{text-align:left;color:var(--muted);padding:0.5rem;border-bottom:1px solid var(--border);font-size:0.75rem;text-transform:uppercase}td{padding:0.5rem;border-bottom:1px solid var(--border)}.empty{color:var(--muted);font-size:0.85rem;padding:1rem 0;text-align:center}.full{grid-column:1/-1}.badge-g{background:#1a3a1a;color:#5cb85c;border:1px solid #2d5a2d;border-radius:3px;padding:0.1rem 0.4rem;font-size:0.72rem}.badge-r{background:#3a1a1a;color:#d9534f;border:1px solid #5a2d2d;border-radius:3px;padding:0.1rem 0.4rem;font-size:0.72rem}.badge-y{background:#3a2f1a;color:#f0ad4e;border:1px solid #5a4a2d;border-radius:3px;padding:0.1rem 0.4rem;font-size:0.72rem}</style></head>
<body><header><span class="logo">&#x2B21; Stockyard</span><span style="color:var(--muted)">/</span><span style="color:var(--cream);font-weight:600">Parcel</span><span class="badge">File Sharing</span></header>
<main><div class="stats"><div class="stat"><div class="stat-value" id="s1">0</div><div class="stat-label">Files</div></div><div class="stat"><div class="stat-value" id="s2">0</div><div class="stat-label">Bytes Stored</div></div><div class="stat"><div class="stat-value" id="s3">FREE</div><div class="stat-label">Tier</div></div></div><div class="grid">
<div class="card"><h2>Upload File</h2>
<div class="form-row"><input type="file" id="f-file" style="flex:1"></div>
<div class="form-row"><input id="f-maxdl" type="number" placeholder="Max downloads (0=unlimited)"><input id="f-exp" type="number" placeholder="Expires in hours (0=never)"></div>
<button class="btn" onclick="uploadFile()">Upload</button>
<div id="upload-result" style="margin-top:0.75rem;font-size:0.8rem;color:var(--leather);word-break:break-all"></div></div>
<div class="card"><h2>Usage</h2>
<p style="font-size:0.82rem;color:var(--muted);line-height:1.6">Files are served at:<br><span style="color:var(--leather);font-family:monospace">GET /d/{token}</span><br><br>Each upload gets a unique token. Set max downloads or expiry for self-destructing links.</p></div>
<div class="card full"><h2>Files</h2>
<table><thead><tr><th>Filename</th><th>Size</th><th>Downloads</th><th>Expires</th><th>Share Link</th><th></th></tr></thead>
<tbody id="files-body"><tr><td colspan="6" class="empty">No files</td></tr></tbody></table></div>
</div></main>
<script>
async function api(m,p,bd){var o={method:m,headers:{"Content-Type":"application/json"}};if(bd)o.body=JSON.stringify(bd);var r=await fetch(p,o);try{return await r.json();}catch(e){return {};}}  
async function load(){var s=await api("GET","/api/stats");var l=await api("GET","/api/limits");document.getElementById("s1").textContent=s.files||0;var bytes=s.total_bytes||0;document.getElementById("s2").textContent=bytes<1048576?Math.round(bytes/1024)+"KB":Math.round(bytes/1048576)+"MB";document.getElementById("s3").textContent=(l.tier||"free").toUpperCase();loadFiles();}
async function loadFiles(){var data=await api("GET","/api/files");var tbody=document.getElementById("files-body");if(!data||!data.length){tbody.innerHTML="<tr><td colspan='6' class='empty'>No files</td></tr>";return;}tbody.innerHTML=data.map(function(f){var url=window.location.origin+"/d/"+f.share_token;var sz=f.size<1048576?Math.round(f.size/1024)+"KB":Math.round(f.size/1048576)+"MB";return "<tr><td style='color:var(--cream)'>"+f.original_name+"</td><td style='color:var(--muted);font-size:0.8rem'>"+sz+"</td><td>"+(f.max_downloads>0?f.downloads+"/"+f.max_downloads:f.downloads)+"</td><td style='font-size:0.75rem;color:var(--muted)'>"+(f.expires_at?new Date(f.expires_at).toLocaleDateString():"Never")+"</td><td><a href='"+url+"' target='_blank' style='color:var(--leather);font-size:0.8rem;word-break:break-all'>/d/"+f.share_token+"</a></td><td><button class='btn btn-sm btn-danger' onclick='deleteFile("+f.id+")'>Del</button></td></tr>";}).join("");}
async function uploadFile(){var fileInput=document.getElementById("f-file");if(!fileInput.files.length){alert("Select a file first");return;}var fd=new FormData();fd.append("file",fileInput.files[0]);var maxdl=document.getElementById("f-maxdl").value;var exp=document.getElementById("f-exp").value;if(maxdl)fd.append("max_downloads",maxdl);if(exp)fd.append("expires_hours",exp);var r=await fetch("/api/upload",{method:"POST",body:fd});var res=await r.json();if(res.error){alert(res.error);return;}var url=window.location.origin+res.download_url;document.getElementById("upload-result").textContent="Link: "+url;fileInput.value="";load();}
async function deleteFile(id){if(!confirm("Delete file?"))return;await api("DELETE","/api/files/"+id);load();}
load();
</script></body></html>`)
